### ISSUE TITLE
Issue with functions with the same name as variables in other scopes.

### ISSUE THREAD

**Issue by theusaf** [Bas950/eslint-plugin-no-one-time-vars#4] opened 2022-03-25 03:56 UTC
In specific conditions, `no-one-time-vars` does not detect some single-use variables. This affects 2.2.0 and 2.2.1.

There is some interesting behavior when you have a function with the same name:
```js
{
  const test = 1;
  console.log(test);
}
{
  const test = 2;
  console.log(test);
}
function test() {}
test();
```
In this case, the second block with the single-use variable is detected, but the first block is not. Adding more blocks results in all of them being detected, except for the first one. With only 1 block, no errors are found.

**Comment by Slowlife01** [comment] 2022-03-25 05:31
Unable to reproduce.
![image](https://user-images.githubusercontent.com/54318514/160060431-61d317ca-c724-4af2-aaa3-2c61d2ff96ff.png)

**Comment by theusaf** [comment] 2022-03-25 05:59
The issue can be seen here: https://github.com/theusaf/eslint-plugin-no-one-time-vars/runs/5687595645?check_suite_focus=true
It can be reproducible if there is a function in addition to the blocks with the same name:
```js
{
  code: `
  {
    const test = "hello world";
    console.log(test);
  }
  const test = () => {};
  test();
  `,
  output: `
  {
    
    console.log("hello world");
  }
  const test = () => {};
  test();
  `,
  errors: [
    {
      message: "Variable 'test' is only used once.",
      type: "VariableDeclarator",
      line: 3
    }
  ]
}
```
This results in the following:
<img width="505" alt="2022-03-24 22_58_51-#1" src="https://user-images.githubusercontent.com/32113157/160063299-89ae663c-cfa8-429f-ba7e-314320dba205.png">

**Comment by Slowlife01** [comment] 2022-03-25 12:47
Should be fixed.

**Closed as completed by Slowlife01** 2022-03-25 12:47 UTC
